[build]
  command = ""
  publish = "/" # Publie la racine du dossier C5 (où se trouve index.html)

[[redirects]]
  from = "/"
  to = "/index.html" # Redirige vers index.html qui se trouve dans C5
  status = 200

[functions]
  directory = "netlify/fonctions"
