[build]
  # Indique à Netlify que le dossier à déployer est le sous-dossier C1
  publish = "C1"
  # Aucune commande de compilation nécessaire
  command = ""

# Redirection essentielle pour le routage de votre assistant (SPA)
# S'assure que si un lien est mal formé, il renvoie toujours vers votre index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
